name: exp_2b
exp_cfg:
  run_name: null
  train_path: "datasets/clouds/38-Cloud/38-Cloud_training"
  C38_path: "datasets/clouds/38-Cloud/38-Cloud_test"
  C38_gtpath: "datasets/clouds/38-Cloud/38-Cloud_test/Entire_scene_gts"
  L8CCA_path: "datasets/clouds/Landsat-Cloud-Cover-Assessment-Validation-Data-Partial"
  vpath: "datasets/clouds/38-Cloud/38-Cloud_test/Natural_False_Color"
  rpath: "artifacts/"
  ppath: null
  vids: ["*"]
  mlflow: False
  train_size: 0.8
  train_img: "LC08_L1TP_035034_20160120_20170224_01_T1"
  balance_train_dataset: False
  balance_val_dataset: False
  balance_snow: False
  snow_imgs_38Cloud: ["LC08_L1TP_064015_20160420_20170223_01_T1",
                      "LC08_L1TP_035035_20160120_20170224_01_T1",
                      "LC08_L1TP_050024_20160520_20170324_01_T1"]
  snow_imgs_L8CCA: ["LC82271192014287LGN00",
                    "LC81321192014054LGN00"]
train_cfg:
  batch_size: 32
  thr: 0.5
  learning_rate: 0.01
  bn_momentum: 0.9
  epochs: 200
  stopping_patience: 20